version: 2.1
orbs: 
  codecov: codecov/codecov@3.2.3

jobs:
  build:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - run:
          name: Test backend
          command: cd backend/ && npm install && npm test
      - run:
          name: Test frontend
          command: cd fronted/ && npm install && npm test
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build