version: 2.1
orbs: 
  codecov: codecov/codecov@3.2.3

jobs:
  build:
    docker:
      - image: cimg/node:current
    working_directory: ~/project/backend
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests and collect coverage
          command: npm test
      - codecov/upload

workflow:
  version: 2.1
  build-test:
    jobs:
      - build